# SemEval 2025 Task 9: The Food Hazard Detection Challenge

---
> Eleni Kechrioti <br />
> Department of Informatics <br />
> Athens University of Economics and Business <br />
> p3210078@aueb.gr

## Introduction

The assignment is structured as follows to ensure clarity and ease of navigation:

- **Root Directory**:
  - **`SemEval 2025 Task 9.ipynb`**: Jupyter Notebook file where the analysis is performed.
  - **`incidents_train.csv`**: The training dataset containing incident data, including titles, descriptions, and corresponding labels for classification tasks.
  - **`incidents_test.csv`**: The test dataset used to evaluate the performance of the trained model.
  - **`incidents_valid.csv`**: The validation dataset.
  - **`/submission`**: A folder containing the total predictions on the validation and testing datasets.

*-Note:* The datasets and folder will not appear when you download the notebook in the folder, but later on, as we will download them from the [SemEval's github page](https://github.com/food-hazard-detection-semeval-2025/food-hazard-detection-semeval-2025.github.io).

*--Note:* For this analysis I used the `text` column as I find that due to the larger description, i.e more information, it gives better results.

<br><br>
### Step 1: Install Required Libraries
For this analysis we will use 

- **scikit-learn**: A machine learning library for Python, providing simple tools for data analysis and modeling, such as classification, regression, and clustering algorithms.
- **TensorFlow**: An open-source machine learning library used to build and train models, especially deep learning architectures like BERT.
- **imblearn**: A library for imbalanced learning, which includes various tools for resampling datasets and handling imbalanced class distributions.
- **PyTorch**: A deep learning library widely used for its flexibility and ease of use in building neural network models.

In [ ]:
%pip install scikit-learn tensorflow imbalanced-learn torch

Once you have done that you can go ahead and run the notebook and start building and evaluating the machine learning models. We will use the following libraries and modules are imported to help in various stages of the machine learning pipeline, including data preprocessing, model training, and evaluation:

- **Pandas** and **NumPy**: For data manipulation and numerical operations.
- **LabelEncoder**: For encoding categorical labels into numeric values for classification tasks.
- **StandardScaler**: For scaling features to standardize the data, improving model performance.
- **RandomForestClassifier**: A powerful ensemble learning method for classification tasks.
- **TensorFlow** and **PyTorch**: Deep learning frameworks for implementing neural networks (though PyTorch is not utilized here).
- **Pipeline**: A utility from scikit-learn that allows chaining transformers and classifiers into a single object for streamlined training and evaluation.
- **ConfusionMatrixDisplay** and **classification_report**: For evaluating model performance with metrics like accuracy, precision, recall, and F1-score.
- **TfidfVectorizer**: For converting text data into numerical features using TF-IDF, which is often used in text classification tasks.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
import random
import tensorflow as tf
import torch
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

### Step 2: Download the data

Let's download our data and take a look at them.

In [2]:
# download training data (labeled):
!curl -O https://raw.githubusercontent.com/food-hazard-detection-semeval-2025/food-hazard-detection-semeval-2025.github.io/refs/heads/main/data/incidents_train.csv

# download testing data (labeled):
!curl -O https://raw.githubusercontent.com/food-hazard-detection-semeval-2025/food-hazard-detection-semeval-2025.github.io/refs/heads/main/data/incidents_test.csv

# download validation data (labeled):
!curl -O https://raw.githubusercontent.com/food-hazard-detection-semeval-2025/food-hazard-detection-semeval-2025.github.io/refs/heads/main/data/incidents_valid.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12.2M  100 12.2M    0     0  11.0M      0  0:00:01  0:00:01 --:--:-- 11.0M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2479k  100 2479k    0     0  3683k      0 --:--:-- --:--:-- --:--:-- 3705k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 1337k    0  2756    0     0   6163      0  0:03:42 --:--:--  0:03:42  6193
100 1337k  100 1337k    0     0  1977k      0 --:--:-- --:--:-- --:--:-- 1983k

### Step 3: Understand the data

In this step, we will load the data from the provided CSV files into variables `trainset`, `testset`, and `validset` respectively. These datasets contain information about food recall incidents, which will be used for classification tasks. The structure of the dataset as you can see from the sample below includes several important columns:

- **year**: The year when the recall was issued.
- **month**: The month when the recall was issued.
- **day**: The day when the recall was issued.
- **country**: The country code where the recall was issued.
- **title**: A brief title describing the recall incident.
- **text**: A detailed description of the recall incident, containing information about the affected products, health hazards, and other relevant details.
- **hazard-category**: The category of the hazard involved in the recall (e.g., allergens, biological, fraud).
- **product-category**: The category of the product affected by the recall (e.g., meat, dairy products).
- **hazard**: A more specific description of the hazard involved (e.g., fish, E. coli).
- **product**: The name or type of the recalled product (e.g., chicken-based products, ground beef).

In [140]:
trainset = pd.read_csv('incidents_train.csv', index_col=0, encoding='utf-8')
trainset.sample(5)

,year,month,day,country,title,text,hazard-category,product-category,hazard,product
4371,2020,8,13,us,Serafin Fishery Issues Allergy Alert on Undecl...,Serafin Fishery is recalling its 8-ounce conta...,allergens,"soups, broths, sauces and condiments",fish and products thereof,dip-sauce
1514,2016,2,8,us,Living Tree Community Foods Recalls Macadamia ...,"Living Tree Community Foods of Berkeley, Calif...",biological,"nuts, nut products and seeds",salmonella,macadamia nuts
2120,2017,3,1,us,"Wayne Farms, LLC Recalls Ready-To-Eat Chicken ...","WASHINGTON, Feb. 28, 2017 – Wayne Farms, LLC, ...",other hazard,"meat, egg and dairy products",processing,chicken based products
3660,2019,8,1,us,Bimbo Bakeries USA Voluntary Recall of Entenma...,"null Bimbo Bakeries USA, Inc. has initiated a ...",foreign bodies,cereals and bakery products,plastic fragment,cookies
858,2013,7,11,us,2009 - Frito-Lay Issues Nationwide Voluntary R...,"FOR IMMEDIATE RELEASE -- PLANO, TX (March 31, ...",biological,"nuts, nut products and seeds",salmonella,pistachio nuts

In [141]:
# load test data:
testset = pd.read_csv('incidents_test.csv', index_col=0)

testset.sample(3)

,year,month,day,country,title,text,hazard-category,product-category,hazard,product
520,2018,3,29,us,Target Corporation Recalls Frozen Ready-To-Eat...,"WASHINGTON, March 29, 2018 – Target Corporatio...",other hazard,"meat, egg and dairy products",improper conditions,other not classified meat products
325,2016,4,20,uk,Argo Poultry recalls Whole Cooked Chickens due...,Argo Foods has instigated a recall as it has b...,fraud,"meat, egg and dairy products",incorrect use by dates,chicken based products
700,2019,10,12,us,"YOUBITE, LLC Recalls Pork Sausage and Turkey S...","WASHINGTON, Oct. 11, 2019 – YOUBITE, LLC, a Ca...",fraud,"meat, egg and dairy products",incorrect labeling,turkey based products

In [142]:
# load validation data:
validset = pd.read_csv('incidents_valid.csv', index_col=0)

validset.sample(3)

,year,month,day,country,title,text,hazard-category,product-category,hazard,product
55,2007,8,2,au,Woolworths Limited—Homebrand Oyster Sauce,PRA No. 2007/9432 Date published 2 Aug 2007 Pr...,allergens,"soups, broths, sauces and condiments",cereals containing gluten and products thereof,oyster sauce
260,2017,4,22,ca,Longo's brand Ontario Lean Ground Veal recalle...,Food Recall Warning - Longo's brand Ontario Le...,biological,"meat, egg and dairy products",escherichia coli,ground beef
367,2019,3,5,au,Peter Bouchier Thai Chicken Stir Fry,Page Content ​Thai Chicken Stir Fry approximat...,allergens,prepared dishes and snacks,peanuts and products thereof,cooked chicken

### Step 4: Data Preprocessing

Before we start modeling, we need to understand the data's distribution and handle missing values, if any. Additionally, we can check the class distribution for different labels, as it will help us decide on techniques for handling imbalanced datasets (e.g., oversampling, undersampling).

This step ensures that the data is clean, consistent, and ready for machine learning tasks. After understanding the data, we can move on to feature extraction and model building.

In [6]:
_ = trainset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5082 entries, 0 to 5983
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              5082 non-null   int64
 1   month             5082 non-null   int64
 2   day               5082 non-null   int64
 3   country           5082 non-null   object
 4   title             5082 non-null   object
 5   text              5082 non-null   object
 6   hazard-category   5082 non-null   object
 7   product-category  5082 non-null   object
 8   hazard            5082 non-null   object
 9   product           5082 non-null   object
dtypes: int64(3), object(7)
memory usage: 436.7+ KB

In [7]:
_ = testset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 997 entries, 0 to 996
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              997 non-null    int64
 1   month             997 non-null    int64
 2   day               997 non-null    int64
 3   country           997 non-null    object
 4   title             997 non-null    object
 5   text              997 non-null    object
 6   hazard-category   997 non-null    object
 7   product-category  997 non-null    object
 8   hazard            997 non-null    object
 9   product           997 non-null    object
dtypes: int64(3), object(7)
memory usage: 85.7+ KB

In [8]:
_ = validset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 565 entries, 0 to 564
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              565 non-null    int64
 1   month             565 non-null    int64
 2   day               565 non-null    int64
 3   country           565 non-null    object
 4   title             565 non-null    object
 5   text              565 non-null    object
 6   hazard-category   565 non-null    object
 7   product-category  565 non-null    object
 8   hazard            565 non-null    object
 9   product           565 non-null    object
dtypes: int64(3), object(7)
memory usage: 48.6+ KB

We can notice from the above that there are not any values missing from our datasets. This means that we do not need to perform any imputation or removal of missing data. All the required columns, such as `title` and `text`, are present, ensuring that we have a complete dataset for training, validation, and testing. 

However as we can see below our dataset shows an imbalanced distribution of categories, with certain hazards and products significantly outnumbering others. The same goes for the columns hazard and product, if you follow the same calculations for those, but it is not shown here as the output is significantly large in rows (128 and 1022 respectively).

In [9]:
from IPython.display import display, HTML

# Get the value counts
hazard_category_counts = trainset['hazard-category'].value_counts().to_frame().rename(columns={'hazard-category': 'Count'})
product_category_counts = trainset['product-category'].value_counts().to_frame().rename(columns={'product-category': 'Count'})

# Display both dataframes side by side using HTML table formatting
display(HTML(f"<table><tr><td>{hazard_category_counts.to_html()}</td><td>{product_category_counts.to_html()}</td></tr></table>"))

Due to this imbalance you can propably guess that any model will be trained very well for categories like `allergens` and `meat, egg and dairy products` but not to others. 

Since there is a significant imbalance in the number of samples for each hazard category, this could lead to poor model performance for the underrepresented classes. There are several ways to address this imbalance:

1. Resampling Techniques:
    - Over-sampling the minority classes (e.g., using SMOTE).
    - Under-sampling the majority classes.
    - A combination of both methods.

2. Class Weight Adjustment:
    - Assign higher weights to the minority classes during model training, so the model will penalize mistakes on minority classes more heavily. Many models (such as Random Forest and Neural Networks) allow you to specify class weights.

Here we will set the "seed", before we start, in various libraries to ensure the reproducibility of the results. When you set the same seed for the random number generator, you will get the same results every time you run the code. Why do we need it though?

- Random processes: Many machine learning algorithms, including Random Forests, neural networks, and others, involve some random processes, such as:
    - Splitting data into training and validation sets
    - Initializing weights in neural networks
    - Bootstrapping samples in Random Forest
- These processes can lead to slightly different results every time you run the code, even if everything else is identical.
- By setting a fixed seed, you ensure that these random processes are initialized in exactly the same way every time, leading to identical results across different runs. This makes it easier to compare models and results.

In [117]:
# Set the seed in all libraries
np.random.seed(30)
random.seed(30)
tf.random.set_seed(30)
torch.manual_seed(30)

Also, before we start here is the evaluation function we will use to evaluate our results, by calculating the macro-F1-score on the predicted labels (hazards_pred & products_pred) using the annotated labels (hazards_true & products_true) as ground truth.

In [162]:
from sklearn.metrics import f1_score

# Function to compute F1 scores for hazards and products
def compute_score(hazards_true, products_true, hazards_pred, products_pred):
    # Compute F1 score for hazards:
    f1_hazards = f1_score(
        hazards_true,  # True labels for hazards
        hazards_pred,  # Predicted labels for hazards
        average='macro'  # Using macro average for F1 score
    )
    # Compute F1 score for products, considering only the cases where the hazard prediction is correct
    f1_products = f1_score(
        products_true[hazards_pred == hazards_true],  # True labels for products where the hazard prediction is correct
        products_pred[hazards_pred == hazards_true],  # Predicted labels for products where the hazard prediction is correct
        average='macro'  # Using macro average for F1 score
    )
    # Return the average of both F1 scores (for hazards and products)
    return (f1_hazards + f1_products) / 2.

## SubTask 1: Hazard and Product category classification

In SubTask 1, we want to predict the type of the hazard and the product. This is a multi-class classification with a single label. Here we will introduce another solution to handle the imbalance of the data. Why don’t we use one of the others mentioned previously?

I did test them, and with every single one I faced difficulties.

- **SMOTE** uses the `k_neighbors` parameter to find the k nearest neighbors and generate synthetic samples based on those neighbors. However, when the dataset is highly imbalanced with a majority class overwhelming others, SMOTE may lead to overfitting, as it generates new samples that may not accurately reflect the minority class distribution. The main issue though here, was that many categories had only one sample and SMOTE could not find the nearest neighbors (which is minimum 2).

- **Under-sampling** method can also be problematic. When trying to under sample the majority classes, I was led to a loss of valuable data from the majority class. Thus, the prediction accuracy was significantly decreasing.

- **Class weights** in classifiers attempt to address the imbalance by giving more importance to the minority class. While this can be effective, it does not always guarantee improved performance, especially when the imbalance is extreme. This was the case here.

Given these challenges, I decided to leverage the **OneVsRest (OvR)** strategy with **RandomForestClassifier** as the base model.

### OneVsRest Classifier for Multi-Class Classification

#### Why OneVsRest?

The OvR strategy trains a separate classifier for each class and handles class imbalance naturally by focusing each classifier on distinguishing a single class from the rest. This avoids the problems of generating synthetic data or overfitting while making the model more robust and interpretable.

- **Simplifies Multi-Class Problem**: Breaks it down into binary classification tasks, making it easier to implement and interpret.
- **Handles Class Imbalance**: Each classifier focuses on distinguishing a single class from the rest, reducing the impact of class imbalance.
- **Efficient**: Easy to implement and computationally efficient, especially with models like **RandomForest** that can handle large feature spaces and provide built-in class balancing.

It is worth mentioning here, that this is not a usual implementation as the OvR strategy is commonly used for multi-label classification and here we have single-label. Although, for all the reasons mentioned above we can use it here.

#### Overview
The code uses the **OneVsRest** strategy for multi-class classification with a **RandomForestClassifier**. Each class has its own classifier, and the final prediction is made based on which classifier is most confident about a sample.

#### Key Components

1. **TfidfVectorizer**:  
   Converts text data (titles) into numerical features using n-grams (2-5 characters). It applies **TF-IDF** weighting to highlight important words while filtering out common or rare terms.

2. **Pipeline**:  
   A `Pipeline` is used to chain the vectorization and classification steps. This ensures smooth data transformation and classification in a single process.

3. **OneVsRestClassifier**:  
   A separate binary classifier is trained for each class. The classifier predicts whether a sample belongs to its class or not, and the final prediction is the class with the highest probability.

4. **RandomForestClassifier**:  
   A **RandomForest** model is used as the base classifier for each binary task.


This code efficiently tackles multi-class classification by using **OneVsRest** with **RandomForest** as the base classifier. It’s especially useful when dealing with imbalanced datasets, as each class gets its own dedicated classifier, and class imbalance is managed through **class weights**.

In [189]:
def train_ovr_classifier(trainset, validset, label):
    # TfidfVectorizer to turn titles into numerical values
    vectorizer = TfidfVectorizer(strip_accents='unicode', analyzer='char', ngram_range=(2,5), max_df=0.5, min_df=5)
    
    # Pipeline with OneVsRestClassifier and RandomForest
    text_clf_ovr = Pipeline([
        ('vect', vectorizer),
        ('clf', OneVsRestClassifier(RandomForestClassifier(n_estimators=200, random_state=30)))
    ])
    
    # Train the model
    text_clf_ovr.fit(trainset['text'], trainset[label])
    
    # Predict
    y_pred = text_clf_ovr.predict(validset['text'])
    
    # Print the classification Report
    print(classification_report(validset[label], y_pred, zero_division=0))
    
    return y_pred  # Return the predictions

Let's see how our algorithm performs

In [ ]:
hazard_cat_preds = train_ovr_classifier(trainset, validset, 'hazard-category')
product_cat_preds = train_ovr_classifier(trainset, validset, 'product-category')

                                precision    recall  f1-score   support

                     allergens       0.93      1.00      0.96       207
                    biological       0.97      0.99      0.98       194
                      chemical       0.86      0.89      0.88        28
food additives and flavourings       1.00      0.50      0.67         2
                foreign bodies       0.88      1.00      0.93        63
                         fraud       0.93      0.61      0.74        41
          organoleptic aspects       0.75      0.38      0.50         8
                  other hazard       0.89      0.57      0.70        14
              packaging defect       0.50      0.12      0.20         8

                      accuracy                           0.93       565
                     macro avg       0.86      0.67      0.73       565
                  weighted avg       0.92      0.93      0.92       565

                                                   precision    recall  f1-score   support

                              alcoholic beverages       1.00      0.71      0.83         7
                      cereals and bakery products       0.68      0.69      0.68        75
     cocoa and cocoa preparations, coffee and tea       0.62      0.87      0.72        15
                                    confectionery       1.00      0.42      0.59        26
dietetic foods, food supplements, fortified foods       0.67      0.71      0.69        14
                                    fats and oils       0.67      0.50      0.57         4
                                   feed materials       0.00      0.00      0.00         1
                            fruits and vegetables       0.80      0.69      0.74        52
                                 herbs and spices       0.58      0.74      0.65        19
                                ices and desserts       0.86      0.75      0.80        24
                     meat, egg and dairy products       0.73      0.95      0.83       146
                          non-alcoholic beverages       0.89      0.89      0.89        19
                     nuts, nut products and seeds       0.81      0.79      0.80        33
                       other food product / mixed       0.67      0.20      0.31        10
                                         pet feed       0.50      1.00      0.67         1
                       prepared dishes and snacks       0.57      0.41      0.48        56
                                          seafood       0.82      0.85      0.84        27
             soups, broths, sauces and condiments       0.74      0.64      0.69        36

                                         accuracy                           0.73       565
                                        macro avg       0.70      0.66      0.65       565
                                     weighted avg       0.74      0.73      0.72       565

### Performance Summary

- **Hazard Categories**: The model performs well on larger categories like `allergens` and `biological`, with high F1-scores (0.96 and 0.98). However, it struggles with rare categories, like `packaging defect`, where F1-scores is 0.20 due to very few samples. However we can see that the algorithm worked for some smaller categories like `food additives and flavourings` that has only 2 samples compared to the 200+ of others and 0.68 on F1 score.
  
- **Product Categories**: Similar to hazard categories, performance is strong for some classes like `alcoholic beverages` (F1 = 0.83) but weak for others with limited samples, like `feed materials`, which gets an F1-score of 0.00.

- **Overall F1 Score**: The macro F1-score is 0.73 for hazard categories and 0.65 for product categories, indicating moderate performance, especially for smaller classes. The weighted F1-score is higher, reflecting the impact of larger classes.

- **General Observations**: The class imbalance significantly impacts performance, with the model performing better on classes with more samples. 

The overall F1-score for SubTask 1 on the valid dataset is 0.72, which is considered well, taking in mind the high number of classes and the imbalance.

In [174]:
print('Score Sub-Task 1:',compute_score(validset['hazard-category'], validset['product-category'], hazard_cat_preds, product_cat_preds))

Score Sub-Task 1: 0.7211688384041834

On the test dataset we see similar results, if we examine each category. The overall performance is 0.65, with hazard category being 0.68 and product category 0.6, which can be expected as the dataset is almost double the size of the validset.

In [175]:
hazard_cat_preds_test = train_ovr_classifier(trainset, testset, 'hazard-category')
product_cat_preds_test = train_ovr_classifier(trainset, testset, 'product-category')

                                precision    recall  f1-score   support

                     allergens       0.94      0.98      0.96       365
                    biological       0.96      0.98      0.97       343
                      chemical       0.94      0.94      0.94        52
food additives and flavourings       1.00      0.25      0.40         4
                foreign bodies       0.88      0.99      0.93       111
                         fraud       0.85      0.67      0.75        75
                     migration       0.00      0.00      0.00         1
          organoleptic aspects       1.00      0.40      0.57        10
                  other hazard       0.71      0.58      0.64        26
              packaging defect       1.00      0.50      0.67        10

                      accuracy                           0.93       997
                     macro avg       0.83      0.63      0.68       997
                  weighted avg       0.93      0.93      0.93       997

                                                   precision    recall  f1-score   support

                              alcoholic beverages       1.00      0.69      0.81        16
                      cereals and bakery products       0.69      0.77      0.73       121
     cocoa and cocoa preparations, coffee and tea       0.72      0.81      0.76        42
                                    confectionery       0.72      0.39      0.51        33
dietetic foods, food supplements, fortified foods       0.62      0.38      0.48        26
                                    fats and oils       1.00      0.67      0.80         6
                   food additives and flavourings       0.00      0.00      0.00         4
                            fruits and vegetables       0.69      0.72      0.70       103
                                 herbs and spices       0.64      0.70      0.67        20
                            honey and royal jelly       0.00      0.00      0.00         2
                                ices and desserts       0.93      0.86      0.89        49
                     meat, egg and dairy products       0.80      0.93      0.86       282
                          non-alcoholic beverages       0.67      0.74      0.70        19
                     nuts, nut products and seeds       0.79      0.70      0.75        54
                       other food product / mixed       0.71      0.38      0.50        13
                                         pet feed       1.00      0.50      0.67         2
                       prepared dishes and snacks       0.67      0.49      0.57        92
                                          seafood       0.83      0.87      0.85        60
             soups, broths, sauces and condiments       0.72      0.81      0.76        52
                                sugars and syrups       0.00      0.00      0.00         1

                                         accuracy                           0.76       997
                                        macro avg       0.66      0.57      0.60       997
                                     weighted avg       0.75      0.76      0.74       997

In [176]:
print('Score Sub-Task 1:',compute_score(testset['hazard-category'], testset['product-category'], hazard_cat_preds_test, product_cat_preds_test))

Score Sub-Task 1: 0.6449519953891107

## SubTask2: Hazard and Product vector classification

In this SubTask we want to predict the exact hazard and product. We will use the same training and predicting algorithm as previously.

The results here are expected to be extremely low, but it can be expected from the reasons we said before. It is also very difficult to expect good results when handling 128 and 1022 categories.

In [ ]:
hazard_preds = train_ovr_classifier(trainset, validset, 'hazard')

                                                 precision    recall  f1-score   support

                                      Aflatoxin       1.00      1.00      1.00         1
                                 abnormal smell       0.00      0.00      0.00         1
                                      allergens       0.00      0.00      0.00         1
                                         almond       0.83      0.71      0.77         7
                         antibiotics, vet drugs       0.00      0.00      0.00         1
                                  bacillus spp.       0.67      1.00      0.80         2
                           bad smell / off odor       0.00      0.00      0.00         1
                                  bone fragment       0.00      0.00      0.00         1
                                     brazil nut       0.00      0.00      0.00         1
                              bulging packaging       0.50      0.33      0.40         3
                                         cashew       1.00      1.00      1.00         3
                    celery and products thereof       1.00      1.00      1.00         1
                                        cereals       0.00      0.00      0.00         1
 cereals containing gluten and products thereof       0.73      0.83      0.78        23
                                       chemical       0.00      0.00      0.00         1
               chemical compound (high content)       0.00      0.00      0.00         1
               chemical compound (unauthorised)       0.00      0.00      0.00         1
                          clostridium botulinum       0.80      1.00      0.89         4
                                      coliforms       1.00      1.00      1.00         1
                                cronobacter spp       0.00      0.00      0.00         1
               crustaceans and products thereof       1.00      1.00      1.00         2
                                     cyclospora       1.00      1.00      1.00         1
                              damaged packaging       0.00      0.00      0.00         1
                    e 425 - konjac unauthorised       1.00      1.00      1.00         1
                      eggs and products thereof       0.87      0.87      0.87        23
                                  enteroviruses       1.00      1.00      1.00         1
                               escherichia coli       0.93      1.00      0.96        27
                      fish and products thereof       0.67      0.40      0.50         5
                                 foreign bodies       0.50      0.33      0.40         3
                                 glass fragment       0.69      0.90      0.78        10
                                       hazelnut       0.00      0.00      0.00         2
                                   heavy metals       1.00      0.67      0.80         3
                        high content of cyanide       0.00      0.00      0.00         1
                            improper conditions       0.00      0.00      0.00         2
                             improper packaging       0.00      0.00      0.00         1
                             incorrect labeling       0.67      0.50      0.57         4
                         incorrect use by dates       0.50      0.67      0.57         3
                                        insects       0.67      1.00      0.80         2
                              inspection issues       0.85      1.00      0.92        11
           insufficient labelling/documentation       0.00      0.00      0.00         2
                       labelling/misdescription       0.67      0.50      0.57         4
                         listeria monocytogenes       0.97      1.00      0.99        74
                                   listeria spp       0.00      0.00      0.00         1
                                 metal fragment       0.80      0.94      0.86        17
                  microbiological contamination       0.00      0.00      0.00         2
                      milk and products thereof       0.80      0.98      0.88        65
                                    misbranding       0.00      0.00      0.00         2
                                 misdescription       0.00      0.00      0.00         3
                                    mislabelled       0.00      0.00      0.00         1
                                         moulds       0.75      1.00      0.86         3
                   mustard and products thereof       1.00      0.80      0.89         5
                                      norovirus       1.00      1.00      1.00         2
                                           nuts       0.00      0.00      0.00         3
                                          other       0.33      0.27      0.30        11
                           other not classified       0.50      0.50      0.50         4
        other not classified biological hazards       1.00      1.00      1.00         1
          other not classified chemical hazards       0.00      0.00      0.00         3
other not classified hazards for foreign bodies       0.00      0.00      0.00         1
                               packaging defect       0.00      0.00      0.00         3
                            pathogenic bacteria       0.00      0.00      0.00         1
                                        patulin       1.00      1.00      1.00         1
                   peanuts and products thereof       0.75      0.88      0.81        24
                                      pecan nut       1.00      0.50      0.67         2
                                 pieces of wood       0.00      0.00      0.00         1
                                  pistachio nut       1.00      1.00      1.00         1
                               plastic fragment       0.62      0.91      0.74        23
               polycyclic aromatic hydrocarbons       1.00      1.00      1.00         1
                            poor hygienic state       0.00      0.00      0.00         1
                  poor or insufficient controls       0.00      0.00      0.00         1
                                     processing       1.00      1.00      1.00         4
                               pseudomonas spp.       1.00      1.00      1.00         1
                               rubber fragments       1.00      0.33      0.50         3
                                     salmonella       0.96      1.00      0.98        69
              sesame seeds and products thereof       0.80      0.80      0.80         5
                  soybeans and products thereof       0.65      0.89      0.76        19
                  specified risk material (srm)       1.00      1.00      1.00         1
                                       spoilage       0.50      0.75      0.60         4
                                 staphylococcus       1.00      1.00      1.00         1
                                         stones       0.00      0.00      0.00         1
                            sulphates/sulphites       1.00      1.00      1.00         1
                                sulphur dioxide       1.00      1.00      1.00         2
                  sulphur dioxide and sulphites       0.91      0.91      0.91        11
                              taste disturbance       0.00      0.00      0.00         1
 too high content of tetrahydrocannabinol (THC)       1.00      1.00      1.00         1
                                          toxin       1.00      0.50      0.67         2
                    unauthorised colour sudan 4       1.00      1.00      1.00         1
                            unauthorised import       1.00      1.00      1.00         1
             unauthorised placing on the market       0.00      0.00      0.00         1
          unauthorised substance ethylene oxide       0.83      0.83      0.83         6
                            undeclared additive       1.00      0.50      0.67         2
                         undeclared constituent       0.00      0.00      0.00         1
                                         walnut       1.00      1.00      1.00         4
                                         yeasts       0.00      0.00      0.00         1

                                       accuracy                           0.82       565
                                      macro avg       0.53      0.53      0.52       565
                                   weighted avg       0.76      0.82      0.79       565

As we can see above it actually does a preety good job predicting the type of hazard. In general 0.52 in F1 score is not good, but given the extrimity of the imbalance and the large amount of categories it seems well enough. The problem here is for the product prediction as the F1 score is only 0.21.

In [180]:

product_preds = train_ovr_classifier(trainset, validset, 'product')

                                                      precision    recall  f1-score   support

                              Catfishes (freshwater)       1.00      1.00      1.00         2
                                     Dried pork meat       0.00      0.00      0.00         1
                               Fishes not identified       0.40      0.40      0.40         5
                 Precooked cooked pork meat products       0.00      0.00      0.00         1
                                     alfalfa sprouts       0.33      1.00      0.50         1
                                               algae       0.00      0.00      0.00         0
                                         almond milk       1.00      1.00      1.00         1
                                     almond products       0.00      0.00      0.00         0
                                             almonds       0.00      0.00      0.00         0
                                           appetizer       0.00      0.00      0.00         1
                                         apple juice       0.00      0.00      0.00         1
                                           artichoke       0.00      0.00      0.00         1
                                            avocados       0.00      0.00      0.00         1
                                           baby food       0.00      0.00      0.00         0
                                        baby spinach       0.00      0.00      0.00         0
                                           baguettes       0.00      0.00      0.00         1
                                     bakery products       0.00      0.00      0.00         1
                                          baking mix       0.00      0.00      0.00         1
                                             baklava       0.00      0.00      0.00         1
                         barbeque flavour corn snack       0.00      0.00      0.00         1
                                                bars       0.00      0.00      0.00         5
                                   basil pesto sauce       1.00      1.00      1.00         1
                                           bean curd       0.00      0.00      0.00         1
                                          bean snack       1.00      1.00      1.00         1
                                      beans - canned       0.00      0.00      0.00         1
                                                beef       1.00      1.00      1.00         1
                                       beef products       0.00      0.00      0.00         0
                                                beer       0.75      1.00      0.86         3
                                          betel nuts       0.00      0.00      0.00         1
                                            biscuits       0.50      0.71      0.59         7
                                        black pepper       0.00      0.00      0.00         1
                                    black peppercorn       0.00      0.00      0.00         1
                                         blue cheese       0.00      0.00      0.00         0
                                    blue poppy seeds       0.00      0.00      0.00         0
                                       bottled water       0.50      0.50      0.50         2
                                         brazil nuts       0.00      0.00      0.00         0
                                               bread       0.25      0.50      0.33         2
                         bread and products therefor       0.00      0.00      0.00         0
                                           bread mix       0.00      0.00      0.00         1
                                   breakfast cereals       1.00      0.50      0.67         2
                                         brie cheese       0.00      0.00      0.00         1
                                            brownies       0.00      0.00      0.00         1
                                           buckwheat       0.00      0.00      0.00         1
                                              bulgur       0.00      0.00      0.00         1
                              burrito (ready to eat)       0.00      0.00      0.00         1
                                              butter       0.00      0.00      0.00         1
                                          butter oil       0.00      0.00      0.00         1
                                               cakes       0.38      0.75      0.50         8
                                             candies       0.33      0.17      0.22         6
                             canned artichoke hearts       0.00      0.00      0.00         0
                                      canned mussels       0.00      0.00      0.00         1
                                 carbonated beverage       0.00      0.00      0.00         1
                                         cauliflower       1.00      1.00      1.00         1
                                             cbd oil       1.00      1.00      1.00         1
                                              cereal       0.00      0.00      0.00         0
                                         cereal bars       0.00      0.00      0.00         2
                              cereal-based baby food       0.00      0.00      0.00         1
                                      cheddar cheese       1.00      1.00      1.00         1
                                              cheese       0.44      1.00      0.61         7
                         cheese - made from raw milk       0.00      0.00      0.00         1
                                     cheese products       0.00      0.00      0.00         0
                                        cheese sauce       0.00      0.00      0.00         1
                                          chia seeds       0.00      0.00      0.00         0
                                             chicken       0.00      0.00      0.00         4
                    chicken and chicken preparations       0.00      0.00      0.00         1
                              chicken based products       0.27      0.87      0.41        15
                                      chicken breast       0.50      0.29      0.36         7
                                       chicken broth       0.00      0.00      0.00         1
                                chicken preparations       0.00      0.00      0.00         7
                           chicken products - frozen       0.00      0.00      0.00         1
                                         chilled ham       0.00      0.00      0.00         2
                               chilled pork sausages       0.00      0.00      0.00         0
                              chilled prepared salad       0.00      0.00      0.00         1
          chilled ready to eat salad and side dishes       0.00      0.00      0.00         1
                                      chilled salads       0.00      0.00      0.00         1
                                       chilli powder       0.00      0.00      0.00         1
                                        chilli sauce       0.00      0.00      0.00         1
                                           chocolate       0.00      0.00      0.00         1
                                      chocolate bars       1.00      0.50      0.67         2
                                     chocolate chips       0.00      0.00      0.00         1
                             chocolate confectionery       0.00      0.00      0.00         1
                                   chocolate dessert       0.00      0.00      0.00         1
                              chocolate drink powder       1.00      1.00      1.00         1
                                    chocolate mousse       0.00      0.00      0.00         1
                                  chocolate pralines       0.00      0.00      0.00         1
                                  chocolate products       0.50      1.00      0.67         2
                                          chocolates       0.00      0.00      0.00         1
                                             chorizo       1.00      1.00      1.00         1
                                               cider       1.00      1.00      1.00         1
                                      cinnamon rolls       0.00      0.00      0.00         1
                                               clams       0.00      0.00      0.00         0
                               coconut almond butter       0.00      0.00      0.00         1
                                       coconut juice       1.00      1.00      1.00         3
                                        coconut milk       0.50      1.00      0.67         1
                                            coconuts       0.00      0.00      0.00         0
                                        coffee beans       0.00      0.00      0.00         0
                                        coffee drink       1.00      1.00      1.00         1
                                          cola drink       0.00      0.00      0.00         1
                                       confectionery       0.00      0.00      0.00         0
                                      cooked chicken       0.00      0.00      0.00         6
                                          cooked ham       0.00      0.00      0.00         1
                                             cookies       0.67      0.89      0.76         9
                                       cooking sauce       0.00      0.00      0.00         2
                                           coriander       0.00      0.00      0.00         0
                                                corn       0.80      0.67      0.73         6
                                            crackers       0.67      1.00      0.80         2
                                        cream cheese       0.00      0.00      0.00         1
                                 cream chocolate pie       0.00      0.00      0.00         1
                    crustaceans and products thereof       0.00      0.00      0.00         1
                                     cured pork meat       0.00      0.00      0.00         1
                                               curry       1.00      0.50      0.67         2
                                         curry paste       0.00      0.00      0.00         0
                       dark chocolate coated almonds       0.00      0.00      0.00         1
                                     dark chocolates       0.40      1.00      0.57         4
                                               dates       0.00      0.00      0.00         0
                                            desserts       0.50      0.33      0.40         3
                                  dietary supplement       0.50      0.50      0.50         6
                                           dip-sauce       0.00      0.00      0.00         2
                                              donuts       1.00      1.00      1.00         1
                                            dressing       0.00      0.00      0.00         1
                                       dried almonds       0.00      0.00      0.00         2
                                        dried apples       0.00      0.00      0.00         2
                                      dried apricots       0.50      1.00      0.67         2
                                     dried beef meat       1.00      1.00      1.00         1
                                          dried figs       1.00      1.00      1.00         1
                                        dried fruits       1.00      0.50      0.67         2
                         dried fruits with chocolate       0.00      0.00      0.00         1
                                     dried mushrooms       1.00      1.00      1.00         1
                                         dried plums       1.00      0.33      0.50         3
                                dried shrimp noodles       0.00      0.00      0.00         1
                           drinking chocolate powder       0.00      0.00      0.00         0
                                         dry sausage       0.00      0.00      0.00         0
                                           dumplings       1.00      1.00      1.00         1
                                                eggs       0.50      1.00      0.67         1
                             energy and protein bars       0.50      1.00      0.67         1
                                        energy drink       0.00      0.00      0.00         2
                                         fajita meal       0.00      0.00      0.00         1
                                      feed materials       0.00      0.00      0.00         1
                                 fermented beef meat       0.00      0.00      0.00         1
                                         feta cheese       0.00      0.00      0.00         2
                                       fish products       0.00      0.00      0.00         1
                                    flavoured drinks       0.00      0.00      0.00         1
                                flavoured soft drink       0.00      0.00      0.00         1
                 flavoured whey protein preparations       1.00      1.00      1.00         1
                                            flaxseed       0.00      0.00      0.00         1
                                               flour       1.00      1.00      1.00         3
                                            focaccia       0.00      0.00      0.00         1
                                     food supplement       0.00      0.00      0.00         1
                                     fresh mushrooms       1.00      1.00      1.00         2
                fresh poultry and poultry prepations       0.00      0.00      0.00         0
                  fresh processed beef meat products       0.00      0.00      0.00         1
                                 fresh whole chicken       0.00      0.00      0.00         1
                                 frozen beef patties       0.00      0.00      0.00         1
                      frozen breaded chicken goujons       0.00      0.00      0.00         1
                                      frozen burgers       0.00      0.00      0.00         1
                                frozen chicken wings       0.00      0.00      0.00         1
                          frozen diced chicken roast       1.00      1.00      1.00         1
                                 frozen doner kebabs       0.00      0.00      0.00         1
                          frozen dumplings with beef       0.00      0.00      0.00         1
                                 frozen fish fillets       1.00      1.00      1.00         1
                                      frozen lobster       0.00      0.00      0.00         0
                            frozen marinated chicken       0.00      0.00      0.00         0
                                         frozen peas       0.00      0.00      0.00         1
                                        frozen pizza       0.00      0.00      0.00         2
                                         frozen pork       0.00      0.00      0.00         1
                            frozen pork preparations       0.00      0.00      0.00         1
              frozen pre-fried breaded fish portions       0.00      0.00      0.00         1
                        frozen ready to cook chicken       0.00      0.00      0.00         1
                                frozen sausage rolls       0.00      0.00      0.00         1
                                   frozen vegetables       0.00      0.00      0.00         0
                                         fruit juice       0.00      0.00      0.00         0
                                          fruit pies       0.00      0.00      0.00         0
                                         fruit salad       0.00      0.00      0.00         0
                               fruits and vegetables       0.00      0.00      0.00         2
                  fully cooked, frozen chicken wings       0.00      0.00      0.00         1
                                       garlic powder       0.00      0.00      0.00         2
                                       ginger powder       0.00      0.00      0.00         1
                                       ginger slices       0.00      0.00      0.00         1
                          glass jars of tartar sauce       0.00      0.00      0.00         1
                      gluten-free barleygrass powder       0.00      0.00      0.00         1
                                         goat cheese       0.00      0.00      0.00         1
                                             granola       0.00      0.00      0.00         0
                                      green cardamon       0.00      0.00      0.00         1
                                grissini breadsticks       0.00      0.00      0.00         1
                                      ground almonds       0.00      0.00      0.00         1
                                         ground beef       0.40      0.75      0.52         8
                                    ground beef meat       0.00      0.00      0.00         1
                                               halva       1.00      0.50      0.67         2
                                                 ham       0.20      0.50      0.29         2
                                          ham slices       0.00      0.00      0.00         1
                                           hazelnuts       0.00      0.00      0.00         1
                                     herbal infusion       0.00      0.00      0.00         1
                                             herring       0.00      0.00      0.00         0
                                   high protein bars       0.00      0.00      0.00         0
                                            hot dogs       0.00      0.00      0.00         1
                                           hot sauce       0.00      0.00      0.00         1
                                           ice cream       0.63      0.85      0.72        20
                                     ice cream cones       0.00      0.00      0.00         1
                                   ices and desserts       0.00      0.00      0.00         0
                                         infant food       0.00      0.00      0.00         1
                                      infant formula       1.00      0.50      0.67         2
                            instant beef noodle soup       0.00      0.00      0.00         1
                                      instant coffee       0.00      0.00      0.00         0
                                                 jam       0.50      0.50      0.50         2
                                             jellies       1.00      1.00      1.00         1
                                                kale       0.00      0.00      0.00         0
                            kefta (frozen meatballs)       0.00      0.00      0.00         1
                                             ketchup       0.00      0.00      0.00         1
                                       korean kimchi       0.00      0.00      0.00         1
                                                lamb       0.00      0.00      0.00         1
                                             lasagne       0.00      0.00      0.00         0

Bringing the total score of this subtask to 0.38

In [ ]:
print('Score Sub-Task 2:',compute_score(validset['hazard'], validset['product'], hazard_preds, product_preds))

Score Sub-Task 2: 0.3758394665645924

For the test dataset we also see simiral results as the valid dataset whith only a smaller decrease of 0.06 in the total score.

In [197]:
hazard_preds_test = train_ovr_classifier(trainset, testset, 'hazard')

                                                 precision    recall  f1-score   support

                                      Aflatoxin       1.00      1.00      1.00         2
                                 abnormal smell       0.00      0.00      0.00         1
                                alcohol content       0.00      0.00      0.00         1
                                      alkaloids       0.00      0.00      0.00         1
                                      allergens       0.00      0.00      0.00         3
                                         almond       0.82      0.69      0.75        13
                                      amygdalin       0.00      0.00      0.00         1
                         antibiotics, vet drugs       1.00      1.00      1.00         1
                                  bacillus spp.       1.00      1.00      1.00         3
                           bad smell / off odor       0.00      0.00      0.00         1
                                  bone fragment       1.00      0.50      0.67         2
                                     brazil nut       0.00      0.00      0.00         1
                              bulging packaging       1.00      0.50      0.67         4
                                         cashew       0.00      0.00      0.00         6
                    celery and products thereof       0.00      0.00      0.00         1
                                        cereals       0.00      0.00      0.00         1
 cereals containing gluten and products thereof       0.73      0.78      0.75        41
                                       chemical       1.00      1.00      1.00         1
               chemical compound (high content)       0.00      0.00      0.00         2
               chemical compound (unauthorised)       0.00      0.00      0.00         2
                          clostridium botulinum       0.88      0.88      0.88         8
                                      coliforms       0.00      0.00      0.00         1
                        compositional deviation       0.00      0.00      0.00         1
                                cronobacter spp       1.00      1.00      1.00         1
               crustaceans and products thereof       1.00      0.33      0.50         3
                                     cyclospora       1.00      1.00      1.00         2
                              damaged packaging       0.00      0.00      0.00         1
                    e 425 - konjac unauthorised       1.00      0.50      0.67         2
                      eggs and products thereof       0.82      0.88      0.85        41
                                  enteroviruses       1.00      1.00      1.00         2
                               escherichia coli       0.89      1.00      0.94        47
                         false marketing claims       0.00      0.00      0.00         1
                      fish and products thereof       0.80      0.50      0.62         8
                                 foreign bodies       0.50      0.20      0.29         5
                                 glass fragment       0.79      0.88      0.83        17
                                       hazelnut       1.00      0.33      0.50         3
                                   heavy metals       1.00      0.33      0.50         6
                         high content of copper       0.00      0.00      0.00         1
                        high content of cyanide       0.33      0.50      0.40         2
                       high content of vitamins       0.00      0.00      0.00         1
                            improper conditions       0.00      0.00      0.00         3
                             improper packaging       0.00      0.00      0.00         1
                             incorrect labeling       0.33      0.12      0.18         8
                         incorrect use by dates       0.50      0.60      0.55         5
                                        insects       0.33      0.25      0.29         4
                              inspection issues       0.62      1.00      0.77        20
           insufficient labelling/documentation       0.00      0.00      0.00         4
                       labelling/misdescription       0.50      0.43      0.46         7
                         listeria monocytogenes       0.96      0.98      0.97       131
                                   listeria spp       0.00      0.00      0.00         1
                                 metal fragment       0.82      0.90      0.86        31
                  microbiological contamination       0.00      0.00      0.00         3
                      milk and products thereof       0.79      0.96      0.86       115
                                    misbranding       0.00      0.00      0.00         3
                                 misdescription       0.00      0.00      0.00         5
                                    mislabelled       0.00      0.00      0.00         1
                  molluscs and products thereof       0.00      0.00      0.00         1
                                         moulds       0.83      1.00      0.91         5
                   mustard and products thereof       0.80      0.80      0.80        10
                      non compliance with HACCP       0.00      0.00      0.00         1
                                      norovirus       0.80      1.00      0.89         4
                                     novel food       0.00      0.00      0.00         1
                                           nuts       0.00      0.00      0.00         6
                                     ochratoxin       0.00      0.00      0.00         0
                                          other       0.30      0.37      0.33        19
                       other misbranding issues       0.00      0.00      0.00         1
                           other not classified       0.57      0.57      0.57         7
        other not classified biological hazards       0.00      0.00      0.00         3
          other not classified chemical hazards       1.00      0.25      0.40         4
other not classified hazards for foreign bodies       0.00      0.00      0.00         2
                               packaging defect       0.50      0.25      0.33         4
                                           pahs       1.00      1.00      1.00         1
     paralytic shellfish poisoning (psp) toxins       0.00      0.00      0.00         1
                            pathogenic bacteria       0.00      0.00      0.00         1
                                        patulin       1.00      1.00      1.00         2
                   peanuts and products thereof       0.80      0.95      0.87        42
                                      pecan nut       0.00      0.00      0.00         3
                                 pieces of wood       0.00      0.00      0.00         1
                                  pistachio nut       1.00      0.50      0.67         2
                               plastic fragment       0.61      0.95      0.75        40
               polycyclic aromatic hydrocarbons       1.00      1.00      1.00         1
                            poor hygienic state       0.00      0.00      0.00         1
                  poor or insufficient controls       0.33      0.50      0.40         2
                                     processing       0.75      0.75      0.75         8
               product category/characteristics       0.00      0.00      0.00         1
                               pseudomonas spp.       1.00      1.00      1.00         1
                               rubber fragments       0.71      0.83      0.77         6
                                     salmonella       0.99      0.97      0.98       122
              sesame seeds and products thereof       1.00      0.88      0.93         8
                  soybeans and products thereof       0.65      0.76      0.70        34
                  specified risk material (srm)       1.00      0.50      0.67         2
                                       spoilage       1.00      0.67      0.80         6
                                 staphylococcus       1.00      1.00      1.00         2
                                         stones       0.00      0.00      0.00         2
                            sulphates/sulphites       1.00      0.50      0.67         2
                                sulphur dioxide       1.00      1.00      1.00         3
                  sulphur dioxide and sulphites       0.72      1.00      0.84        18
                              taste disturbance       0.00      0.00      0.00         1
 too high content of tetrahydrocannabinol (THC)       0.00      0.00      0.00         1
                                          toxin       0.75      0.75      0.75         4
                    unauthorised colour sudan 4       0.00      0.00      0.00         1
                            unauthorised import       0.00      0.00      0.00         1
             unauthorised placing on the market       0.00      0.00      0.00         1
          unauthorised substance ethylene oxide       0.83      1.00      0.91        10
              unauthorised substance sildenafil       0.00      0.00      0.00         1
                            undeclared additive       0.75      1.00      0.86         3
                         undeclared constituent       0.00      0.00      0.00         2
                                     vibrio spp       1.00      1.00      1.00         1
                                          virus       1.00      1.00      1.00         1
                                         walnut       0.67      0.33      0.44         6
                                         yeasts       0.00      0.00      0.00         1

                                       accuracy                           0.79       997
                                      macro avg       0.46      0.42      0.42       997
                                   weighted avg       0.75      0.79      0.76       997

In [198]:
product_preds_test = train_ovr_classifier(trainset, testset, 'product')

                                                               precision    recall  f1-score   support

                                       Catfishes (freshwater)       0.40      0.67      0.50         3
                                              Dried pork meat       0.00      0.00      0.00         1
                                        Fishes not identified       0.42      0.62      0.50         8
                                     Not classified pork meat       0.00      0.00      0.00         3
                          Precooked cooked pork meat products       0.00      0.00      0.00         1
                                            Saurida (generic)       0.00      0.00      0.00         1
                           Torpedo-shaped catfishes (generic)       0.00      0.00      0.00         0
                                                Veggie Burger       0.50      1.00      0.67         1
                                              adobo seasoning       0.00      0.00      0.00         0
                                              alfalfa sprouts       0.00      0.00      0.00         0
                                                        algae       1.00      1.00      1.00         1
                                               almond kernels       0.00      0.00      0.00         1
                                              almond products       0.00      0.00      0.00         1
                                                      almonds       0.00      0.00      0.00         0
                                                     amaranth       0.00      0.00      0.00         2
                                                  apple juice       0.00      0.00      0.00         0
                                                       apples       0.00      0.00      0.00         1
                                              apricot kernels       0.00      0.00      0.00         0
                                             assorted baklava       0.00      0.00      0.00         1
                                                    baby food       0.50      1.00      0.67         2
                                           baby food - canned       0.00      0.00      0.00         1
                                                 baby spinach       0.00      0.00      0.00         0
                                              bakery products       1.00      0.25      0.40         4
                                                   baking mix       0.00      0.00      0.00         3
                                                       barley       0.00      0.00      0.00         1
                                                         bars       0.50      0.25      0.33         4
                                                        basil       0.00      0.00      0.00         0
                                            basil pesto sauce       0.40      0.67      0.50         3
                                                   batter mix       0.00      0.00      0.00         1
                                                    bean curd       0.00      0.00      0.00         1
                                                   bean paste       0.00      0.00      0.00         0
                                                   bean sauce       0.00      0.00      0.00         0
                                                 bean sprouts       1.00      0.50      0.67         2
                                                         beef       0.00      0.00      0.00         5
                                                 beef burrito       0.00      0.00      0.00         0
                                                    beef cuts       0.00      0.00      0.00         1
                                                    beef meat       0.00      0.00      0.00         1
                                                beef products       0.12      0.20      0.15         5
                                                  beef tongue       0.00      0.00      0.00         2
                                                         beer       0.29      0.50      0.36         4
                   bilberry extract used in a food supplement       0.00      0.00      0.00         0
                                                     biscuits       0.33      0.38      0.35         8
                                       bitter apricot kernels       0.00      0.00      0.00         1
                                                 black pepper       0.00      0.00      0.00         1
                                                  blue cheese       0.50      1.00      0.67         1
                                             blue poppy seeds       0.00      0.00      0.00         1
                                                  blueberries       0.00      0.00      0.00         1
                                                boneless beef       0.00      0.00      0.00         2
                                      bottled flavoured water       0.00      0.00      0.00         1
                                bottled natural mineral water       0.00      0.00      0.00         1
                                                bottled water       0.00      0.00      0.00         1
                                        bovine meat and offal       0.00      0.00      0.00         0
                                                  brazil nuts       0.00      0.00      0.00         0
                                                        bread       0.56      0.62      0.59         8
                                  bread and products therefor       0.00      0.00      0.00         2
                                            breakfast cereals       0.67      0.50      0.57         4
                                               brewer's yeast       1.00      1.00      1.00         1
                                                     broccoli       1.00      0.50      0.67         4
                                                     brownies       0.00      0.00      0.00         3
                                                       bulgur       0.00      0.00      0.00         1
                                                         buns       0.50      0.50      0.50         2
                                       burrito (ready to eat)       1.00      1.00      1.00         1
                                                       butter       0.00      0.00      0.00         2
                                                      cabbage       0.00      0.00      0.00         1
                                              cake decoration       0.00      0.00      0.00         1
                                                        cakes       0.46      0.79      0.58        14
                                                    camembert       1.00      0.50      0.67         2
                                                      candies       0.50      0.38      0.43         8
                                                  canned corn       0.00      0.00      0.00         1
                                               canned mussels       0.00      0.00      0.00         0
                                            carbonated  water       0.00      0.00      0.00         0
                                       carbonated apple juice       0.00      0.00      0.00         2
                                          carbonated beverage       0.00      0.00      0.00         2
                                   carbonated/sparkling water       0.00      0.00      0.00         1
                                                       cashew       0.00      0.00      0.00         3
                                                  cauliflower       1.00      1.00      1.00         1
                                                 cbd products       0.00      0.00      0.00         1
                                                       cereal       0.50      1.00      0.67         1
                                                  cereal bars       0.00      0.00      0.00         2
                                                 cereal drink       1.00      1.00      1.00         1
                                       cereal-based baby food       0.00      0.00      0.00         1
                                                      cereals       0.00      0.00      0.00         1
                                               cheddar cheese       0.25      0.50      0.33         2
                                                       cheese       0.24      0.56      0.33         9
                   cheese &amp; onion flavoured potato crisps       0.00      0.00      0.00         1
                                   cheese (taleggio capriolo)       0.00      0.00      0.00         1
                                                   cheese dip       0.00      0.00      0.00         0
                                              cheese products       0.00      0.00      0.00         0
                                              cheese sausages       0.00      0.00      0.00         1
                                                     cherries       0.00      0.00      0.00         1
                                                   chia seeds       1.00      1.00      1.00         2
                                                      chicken       0.00      0.00      0.00         1
                             chicken and chicken preparations       0.00      0.00      0.00         1
                                       chicken based products       0.38      0.71      0.49        31
                                               chicken breast       0.00      0.00      0.00         6
                                                 chicken meat       0.00      0.00      0.00         1
                                        chicken meat products       0.00      0.00      0.00         1
                                          chicken noodle soup       1.00      0.50      0.67         2
                                                  chicken pie       0.00      0.00      0.00         1
                                         chicken preparations       0.25      0.25      0.25         4
                                    chicken products - frozen       0.00      0.00      0.00         1
                                               chicken slices       0.00      0.00      0.00         1
                                               chicken spices       0.00      0.00      0.00         1
                                                    chickpeas       0.00      0.00      0.00         1
                                          chilled beef steaks       0.00      0.00      0.00         1
                          chilled pork meat and pork products       0.00      0.00      0.00         1
                                               chilled salads       0.00      0.00      0.00         1
                                      chilled smoked sausages       0.00      0.00      0.00         1
                                                 chilli paste       1.00      1.00      1.00         1
                                                 chilli sauce       1.00      1.00      1.00         1
                                                    chocolate       0.00      0.00      0.00         3
                             chocolate and chocolate products       0.00      0.00      0.00         1
                              chocolate and products therefor       0.00      0.00      0.00         0
              chocolate and strawberry flavoured cyclone milk       0.00      0.00      0.00         1
                                               chocolate bars       0.70      1.00      0.82         7
                                              chocolate chips       1.00      1.00      1.00         2
                                               chocolate eggs       0.50      0.50      0.50         2
                                           chocolate products       0.00      0.00      0.00         0
                                           chocolate truffles       0.00      0.00      0.00         2
                                                   chocolates       1.00      0.33      0.50         3
                                                      chorizo       0.20      1.00      0.33         1
                                              chorizo sausage       0.00      0.00      0.00         1
                                                        cider       1.00      0.50      0.67         2
                                                        clams       0.00      0.00      0.00         1
                                                coconut juice       0.50      1.00      0.67         1
                                                 coconut milk       0.00      0.00      0.00         1
                                                  coconut oil       0.00      0.00      0.00         1
                                                     coconuts       0.44      1.00      0.62         4
                                                          cod       0.00      0.00      0.00         2
                                                 coffee beans       0.00      0.00      0.00         2
                                                 coffee drink       0.00      0.00      0.00         0
                                          concentrated apples       1.00      1.00      1.00         1
                                                confectionery       0.00      0.00      0.00         1
                                       confectionery products       0.00      0.00      0.00         1
                                               cooked chicken       0.00      0.00      0.00         1
                                              cooked sausages       0.00      0.00      0.00         0
                                                      cookies       0.59      0.93      0.72        14
                                                cooking sauce       0.00      0.00      0.00         1
                                                    coriander       0.00      0.00      0.00         2
                                                         corn       0.50      0.83      0.62         6
                                                  cottage pie       0.00      0.00      0.00         1
                                                   courgettes       0.00      0.00      0.00         1
                                                        crabs       0.00      0.00      0.00         1
                                                     crackers       0.33      1.00      0.50         1
                                                 cream cheese       0.00      0.00      0.00         1
                                                   crispbread       0.00      0.00      0.00         0
                                                   croissants       1.00      1.00      1.00         2
                                                    cucumbers       0.00      0.00      0.00         1
                                                 cumin powder       0.00      0.00      0.00         0
                                              cured pork meat       0.00      0.00      0.00         0
                                                        curry       0.75      1.00      0.86         3
                                                      custard       0.50      0.33      0.40         3
                                         custard cream powder       0.00      0.00      0.00         1
                                              dark chocolates       0.50      0.86      0.63         7
                                                        dates       0.33      0.33      0.33         3
                                                     desserts       0.50      0.67      0.57         3
                                           dietary supplement       1.00      0.50      0.67         4
                                                    dip-sauce       0.50      0.20      0.29         5
                                                dipping sauce       0.00      0.00      0.00         1
                                                     dressing       0.00      0.00      0.00         1
                                              dressing sauces       0.00      0.00      0.00         1
                                  dried and candied fruit mix       0.00      0.00      0.00         1
                                                 dried apples       0.00      0.00      0.00         0
                                        dried apricot kernels       0.00      0.00      0.00         1
                                               dried apricots       0.00      0.00      0.00         0
                                              dried beef meat       0.50      0.67      0.57         3
                                         dried chilli peppers       0.00      0.00      0.00         0
                                            dried cranberries       0.00      0.00      0.00         1
                                          dried elder berries       0.00      0.00      0.00         0
           dried herb powder ashwagandha (withania somnifera)       1.00      1.00      1.00         1
                                                  dried plums       0.00      0.00      0.00         1
                                          dried pork sausages       0.00      0.00      0.00         1
                   dried shitake mushrooms (lentinula edodes)       1.00      1.00      1.00         1
                                         dried shrimp noodles       1.00      1.00      1.00         1
                                    drinking chocolate powder       0.00      0.00      0.00         1
                                                      dry ham       0.00      0.00      0.00         1
                                                         duck       0.00      0.00      0.00         1
                                                    dumplings       0.33      0.50      0.40         2
                                                  egg protein       0.00      0.00      0.00         1
                                                         eggs       0.67      0.75      0.71         8
                                                 energy drink       0.00      0.00      0.00         2
                                        essences and extracts       0.00      0.00      0.00         1
                                     extra hot chilli peppers       0.00      0.00      0.00         1
                                                 fennel seeds       0.00      0.00      0.00         1
                                                  feta cheese       1.00      0.43      0.60         7
                                       fish and fish products       0.00      0.00      0.00         2
                                                fish products       0.00      0.00      0.00         2
                                                     fish roe       0.00      0.00      0.00         0
                                       flavoured potato chips       1.00      0.33      0.50         3
                                                     flavours       0.00      0.00      0.00         1
                                   flounders, halibuts, soles       0.00      0.00      0.00         0
                                                        flour       0.75      1.00      0.86         3
                                              food supplement       0.00      0.00      0.00         3

In [199]:
print('Score Sub-Task 2:',compute_score(testset['hazard'], testset['product'], hazard_preds_test, product_preds_test))

Score Sub-Task 2: 0.3151205178410622

Finally, we can make csv files for our valid and test dataset with the real values and the predicted in a zip folder named submission.

In [ ]:
import os
from shutil import make_archive

testset['hazard-category'] = hazard_cat_preds_test
testset['product-category'] = product_cat_preds_test
testset['hazard'] = hazard_preds_test
testset['product'] = product_preds_test
validset['hazard-category'] = hazard_cat_preds
validset['product-category'] = product_cat_preds
validset['hazard'] = hazard_preds
validset['product'] = product_preds

# save predictions to a new folder:
os.makedirs('./submission/', exist_ok=True)
testset[['hazard-category', 'product-category', 'hazard', 'product']].to_csv('./submission/submission_test.csv')
validset[['hazard-category', 'product-category', 'hazard', 'product']].to_csv('./submission/submission_valid.csv')

make_archive('./submission', 'zip', './submission')

'c:\\Users\\eleni\\Desktop\\amm\\food_hazard\\submission.zip'